---
title: "Rmcorr for ICED"
author: "Luis Sandoval-Araujo"
date: '2023-04-05'
output: html_document
---
```{r}
#importing libraries
library(rmcorr)
library(dplyr)
library(data.table)
library(tidyverse)
library(stringr)
```

```{r}
#testing rmcorr using five different participants
#gonna random number generator this to pick which participants

floor(runif(5, min=1, max=128))
```
```{r}
#picked the closest participants to randomly generated numbers 13, 82, 118, 50, and 26
#comes out to PR011, PR084, PR117, PR044, and PR025

PR011 = read.csv('C:/Users/Luis/Box/R15 Sensor Preprocessing and Analysis/EMAPhysioComparisons/Participant Matched Data/PhysioEMA_Match_PR011.csv')
PR025 = read.csv('C:/Users/Luis/Box/R15 Sensor Preprocessing and Analysis/EMAPhysioComparisons/Participant Matched Data/PhysioEMA_Match_PR025.csv')
PR044 = read.csv('C:/Users/Luis/Box/R15 Sensor Preprocessing and Analysis/EMAPhysioComparisons/Participant Matched Data/PhysioEMA_Match_PR044.csv')
PR084 = read.csv('C:/Users/Luis/Box/R15 Sensor Preprocessing and Analysis/EMAPhysioComparisons/Participant Matched Data/PhysioEMA_Match_PR084.csv')
PR117 = read.csv('C:/Users/Luis/Box/R15 Sensor Preprocessing and Analysis/EMAPhysioComparisons/Participant Matched Data/PhysioEMA_Match_PR117.csv')
```


```{r}
#let's take a look at some data first
PR117
```
```{r}
#preparing the data
#steps of the process are as follows:
#1. Add column to each dataframe designating the participant ID
#2. Append datasets together
#We'll start by adding participant IDs, column labelled pid

PR011a = PR011 %>%
  mutate(pid = 'PR011', .before = 'X')
PR025a = PR025 %>%
  mutate(pid = 'PR025', .before = 'X')
PR044a = PR044 %>%
  mutate(pid = 'PR044', .before = 'X')
PR084a = PR084 %>%
  mutate(pid = 'PR084', .before = 'X')
PR117a = PR117 %>%
  mutate(pid = 'PR117', .before = 'X')
```

```{r}
#merging dataframes together, testing first

data = rbind(PR011a, PR025a, PR044a, PR084a, PR117a)
data
```
```{r}
#we're doing the correlations now

rmc.out = rmcorr('pid', 'HR_Mean', 'fowg', data)
rmc.out
```
```{r}
plot(rmc.out, overall = T)
```

```{r}
print(rmc.out)
```
```{r}
#reading the rest of my files in
dat_files = list.files("C:/Users/Luis/Box/R15 Sensor Preprocessing and Analysis/EMAPhysioComparisons/Participant Matched Data/", pattern = '.csv')

dat_files

setwd('C:/Users/Luis/Box/R15 Sensor Preprocessing and Analysis/EMAPhysioComparisons/Participant Matched Data/')
data2 = map_df(dat_files, ~read_csv(.x) %>%
        mutate(pid = str_remove_all(.x, ".csv")))
  
```

```{r}
data2 %>%
  transform(pid=str_replace(pid, "PhysioEMA_Match_", ""))
```

```{r}
data3 = relocate(data2, 'pid', .before = ...1)

data3 = data3 %>%
  transform(pid=str_replace(pid, "PhysioEMA_Match_", ""))
data3 = data3[-27,]
data3
```

```{r}
rmc.out2 = rmcorr('pid', 'TEMP_Mean', 'feelfat', data3)
rmc.out2
```
```{r}
plot(rmc.out2, overall = T)
```

```{r}
#dx values for currentdx1 
#1 = AN, 2 = BN, 3 = BED, 4 = OSFED, 5 = ARFID
diag = read.csv('C:/Users/Luis/Desktop/dx.csv')
diag
```
```{r}
#renaming column then merging dataframes
colnames(diag)[1] = "pid"
data4 = left_join(data3, diag, by="pid")
data4
write.csv(data4, "C:/Users/Luis/Desktop\\PhysioEMAdx.csv", row.names = FALSE)
```
```{r}
#making the groups
andata = subset(data4, data4$currentdx1_ade7bc == 1)
bndata = subset(data4, data4$currentdx1_ade7bc == 2)
osfeddata = subset(data4, data4$currentdx1_ade7bc == 4)
activedata = subset(data4, data4$diagnostic_status == 3)
remissiondata = subset(data4, data4$diagnostic_status == 2)
```
```{r}
unique(data4$pid)
```

```{r}
#this is an example using BN data
rmc.out3 = rmcorr('pid', 'HR_Mean', 'fowg', activedata)
rmc.out3
plot(rmc.out3, overall = T)
```
```{r}
#AN group

an_hrmean_fowg = rmcorr('pid', 'HR_Mean', 'fowg', andata)
an_hrstdev_fowg = rmcorr('pid', 'HR_Stdev', 'fowg', andata)
#an_hrmad_fowg = rmcorr('pid', 'HR_MAD', 'feelfat', andata)

an_hrmean_fowg
an_hrstdev_fowg
#an_hrmad_fowg

plot(an_hrmean_fowg, overall = T)
plot(an_hrstdev_fowg, overall = T)
#plot(an_hrmad_fowg, overall = T)
```
```{r}
andata
```

```{r}
#testing calculating z-scores
PR003 = subset(andata, andata$pid == 'PR003')
andata_z = scale(PR003$HR_Mean)
andata_z
```

```{r}
PR003$HR_Mean_Z = andata_z
PR003
```

```{r}
datasplit = lapply(split(data4, data4$pid), function(x) x$HR_Mean_z = scale(x$HR_Mean))
```

```{r}
datasplit
class(datasplit)
```

```{r}
dsdf = data.frame(pid = rep(names(datasplit), sapply(datasplit, length)), HR_Mean_Z = unlist(datasplit))
dsdf
```

```{r}
data5 = data4
data5['HR_Mean_Z'] = dsdf['HR_Mean_Z']
data5
```

```{r}
datasplit = lapply(split(data4, data4$pid), function(x) x$fowg_z = scale(x$fowg))
dsdf = data.frame(pid = rep(names(datasplit), sapply(datasplit, length)), fowg_Z = unlist(datasplit))
data5['fowg_Z'] = dsdf['fowg_Z']
data5
```

```{r}
datasplit = lapply(split(data4, data4$pid), function(x) x$feelfat_z = scale(x$feelfat))
dsdf = data.frame(pid = rep(names(datasplit), sapply(datasplit, length)), feelfat_Z = unlist(datasplit))
data5['feelfat_Z'] = dsdf['feelfat_Z']
data5
```

```{r}
all_hrmean_fowg = rmcorr('pid', 'HR_Mean', 'fowg', data5)
all_hrmean_fowgz = rmcorr('pid', 'HR_Mean', 'fowg_Z', data5)
all_hrmeanz_fowgz = rmcorr('pid', 'HR_Mean_Z', 'fowg_Z', data5)


all_hrmean_fowg
all_hrmean_fowgz
all_hrmeanz_fowgz

plot(all_hrmean_fowg, overall = T)
plot(all_hrmean_fowgz, overall = T)
plot(all_hrmeanz_fowgz, overall = T)
```

